# Generated by Django 5.0.7 on 2024-11-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_description_chaivariety_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default='This is our newly launched chai', max_length=500),
        ),
        migrations.AlterField(
            model_name='chaivariety',
            name='type',
            field=models.CharField(choices=[('ML', 'Masala'), ('GR', 'Ginger'), ('KL', 'Kiwi'), ('PL', 'Plain'), ('EL', 'Elaichi')], max_length=2),
        ),
    ]
