# Generated by Django 5.0.7 on 2024-11-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaivariety_slug_alter_chaivariety_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaivariety',
            name='slug',
        ),
    ]
